# -*- coding: utf-8 -*-
"""Ejercicios_practicas_pandas_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pr69v8YAxidjMl1koBJU1WFkvi5AadiS

**Ejercicios de práctica**  
Pandas (1)  
**DataFrames, selección, filtros y agrupación**  
A. Conocer el DataFrame

1. Complete la instrucción para conocer el número de filas y de columnas.
"""

import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/plotly/datasets/master/supermarket_Sales.csv"
data = pd.read_csv(url)

data = data.rename(columns={
    'Tax 5%': 'Tax',
    'Cost of goods sold': 'Cogs',
    'Gross margin percentage': 'Gross margin pct',
    'Customer stratification rating': 'Rating'
})

data.columns = (
    data.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

print(data.shape)

"""El primer número corresponde a los registros o filas que serian los (1000) y el segundo corresponde a las variables o columnas (17).

2. Muestre los nombres de las columnas, el tipo de dato de cada una y las tres primeras
ventas registradas.
"""

print(data.columns)
print(data.dtypes)
data.head(3)

"""**B. Seleccionar datos**  
3. Construya un subconjunto que contenga únicamente product_line, quantity y total.
"""

resultado = data[['product_line', 'quantity', 'total']]
resultado.head()

"""4. Antes de ejecutar, anote qué objeto devuelve cada línea. Después compruébelo."""

print(type(data['total']))
print(type(data[['total']]))

"""**Respuesta:** La segunda línea devuelve un DataFrame porque la columna total se está seleccionando dentro de una lista, utilizando doble corchete. Aunque se selecciona una sola columna, pandas conserva la estructura de DataFrame.

5. Las dos instrucciones deben mostrar la línea de producto de la fila con índice 7. La primera trabaja con etiquetas y la segunda con posiciones.
"""

print(data.loc[7, 'product_line'])
print(data.iloc[7, 5])

"""**Respuesta:** La segunda instrucción es más frágil porque iloc trabaja con posiciones. Si cambia el orden de las columnas, la posición 5 podría corresponder a otra variable.

**C. Filtrar filas**  
6. Conserve únicamente las ventas de más de ocho unidades y cuente cuántas son.
"""

mascara = data['quantity'] > 8
resultado = data[mascara]
print(resultado.shape[0])

"""7. Obtenga únicamente las ventas de la sucursal C cuyo total sea mayor de 300 USD."""

mascara = (data['branch'] == 'C') & (data['total'] > 300)
resultado = data[mascara]
print(resultado.shape)

"""8. La instrucción comentada falla porque or no funciona entre columnas de pandas.
Reescriba el filtro con una sola llamada que reciba la lista de líneas de producto.
"""

# Instruccion incorrecta:
# mascara = data['product_line'] == 'Food and beverages'
# or 'Fashion accessories'
mascara = data['product_line'].isin(['Food and beverages', 'Fashion accessories'])
print(data[mascara].shape[0])

"""9. Obtenga las ventas de las sucursales A y C cuyo total se encuentre entre 200 y 500
USD, mostrando solamente branch, product_line, quantity y total
"""

mascara = (data['branch'].isin (['A', 'C'])) & (data['total'].between(200, 500))
resultado = data.loc[mascara, ['branch', 'product_line', 'quantity', 'total']]
resultado.head()

"""**Respuesta:** La ventaja es que se pueden filtrar las filas y seleccionar únicamente las columnas necesarias en una sola instrucción, haciendo el código más directo.

**D. Crear información nueva**  
Cree la columna valor_unitario dividiendo el total entre la cantidad. Resuélvalo sin
escribir un ciclo for.
"""

data['valor_unitario'] = data['total'] / data['quantity']
print(data['valor_unitario'].head(3).round(2))

"""11. Marque como volumen las ventas de seis unidades o más y como menor todas las
demás.
"""

data['tipo_compra'] = np.where(data['quantity']>= 6, 'volumen', 'menor')
print(data['tipo_compra'].value_counts())

"""**Respuesta:** No fue necesario recorrer las filas una por una porque pandas y NumPy permiten aplicar una condición directamente sobre toda la columna.

**E. Agrupar para responder preguntas**

12. ¿Cuánto ingreso genera cada sucursal?     
BÁSICO
Complete la agrupación que responde la pregunta.
"""

resumen = (
data
.groupby('branch')['total']
.sum()
)
print(resumen.round(2))

"""13. ¿Cuántas facturas registra cada método de pago?   
INTERMEDIO
Complete la columna sobre la que se cuenta y la operación correspondiente.
"""

resumen = (
data
.groupby('payment')['invoice_id']
.count()
)
print(resumen)

"""**Respuesta:** Cada fila del resultado representa un método de pago y muestra la cantidad de facturas registradas mediante ese método.

14. Varias métricas por método de pago   
AVANZADO
¿Cuántas facturas, cuántas unidades y cuánto ingreso deja cada método de pago? Una
sola agrupación debe entregar las tres métricas con nombres explícitos.
"""

resumen = (
data
.groupby('payment')
.agg(
facturas=('invoice_id', 'size'),
unidades=('quantity', 'sum'),
ingreso=('total', 'sum'),
)
.reset_index()
)
print(resumen.round(2))

"""**F. Integrar información**  
15. Agregar la zona de cada sucursal   
INTERMEDIO
La tabla de ventas no indica en qué zona está cada sucursal. Esa información vive en
un catálogo aparte. Intégrela conservando todas las ventas.
"""

sucursales = pd.DataFrame({
'branch': ['A', 'B', 'C'],
'zona': ['Centro', 'Norte', 'Sur']
})
resultado = data.merge(
sucursales,
on='branch',
how='left'
)
print(resultado.shape)
resultado[['branch', 'city', 'zona', 'total']].head()

"""*¿qué condición deben cumplir dos tablas para poder integrarse? *

**Respuesta:** Las dos tablas deben tener una clave o columna común
que permita relacionar sus registros.

16. La sucursal líder entre los clientes Member  
 AVANZADO
Considere únicamente las ventas de clientes de tipo Member. Determine qué sucursal
genera el mayor ingreso total y cuál es su ticket promedio, entendido como el ingreso
dividido entre el número de facturas. Escriba el código completo: aquí no hay espacios
para completar.
"""

# 1. Filtrar las ventas de clientes Member
member = data[
    data['customer_type'] == 'Member'
]
# 2. Agrupar por sucursal: numero de facturas e ingreso total
resumen = (
    member
    .groupby('branch')
    .agg(
        facturas=('invoice_id', 'size'),
        ingreso=('total', 'sum')
    )
    .reset_index()
)
# 3. Calcular la columna ticket_promedio
resumen['ticket_promedio'] = (
    resumen['ingreso'] /
    resumen['facturas']
)
# 4. Ordenar de mayor a menor ingreso
resumen = resumen.sort_values(
    'ingreso',
    ascending=False
)
# 5. Escribir la conclusion
print(resumen.round(2))

"""**¿qué sucursal lidera y qué indica su ticket promedio frente a las otras dos?**

**Respuesta:** La sucursal C es la que genera mayor ingreso con 56.881,28 y tiene un ticket promedio de 336,58, superior al de las sucursales B y A. Esto indica que, en promedio, los clientes Member realizan compras de mayor valor en esta sucursal.

"""