# -*- coding: utf-8 -*-
"""Taller_funciones_Python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nXjQ28vnMILrspz3wsfBRFrF10gsFz2
"""



"""***TALLER 1***
---
**Fundamentos Python_1**

**Paradigmas de programación y estructuras de control**

**A. De lalogica a la decisiòn**

1. Completa una decisión simple
Completa la condición para mostrar “Mayor de edad” cuando la variable edad sea mayor o igual a 18.
"""

edad = 20
if edad >=18:
  print("Mayor de edad")

"""2. Completa la estructura para clasificar una temperatura como “Alta” si supera 30 grados y “Normal” en caso contrario."""

temperatura = 32
if temperatura > 30:
  print("Alta")
else:
  print("Normal")

"""3. Sin ejecutar, escribe exactamente qué imprimirá el programa."""

numero=7
if numero % 2 ==0:
  print("Par")
else:
  print("impar")

"""**Respuesta:** impar

**B. Múltiples condiciones**

if / elif / else y orden de evaluación

4. Agrega las dos expresiones faltantes para clasificar la nota.
"""

nota=4.2
if nota>=4.5:
  print("Excelente")
elif nota>= 4.0:
  print("Muy buen desempeño")
elif nota>=3.5:
  print("Aprobado")
else:
  print("No Aprobado")

"""5. El programa pretende mostrar “Excelente” para notas de 4.5 o más. Reescribe únicamente el
bloque condicional en el orden correcto.
"""

nota=4.8
if nota>=4.5:
  print("Excelente")
elif nota >=3.0:
  print("Aprobado")

"""**Respuesta:** Excelente

6. Escribe la salida para valor = 12. Después indica cuál condición fue la primera verdadera.
"""

valor=12
if valor <5:
  print("A")
elif valor <10:
  print("B")
elif valor <15:
  print("C")
else:
  print("D")

"""**Respuesta:**
 C

**C. Operadores lógicos**

*Construye condiciones con and, or y not*

7. Completa el operador lógico para permitir acceso solo cuando ambas variables sean
verdaderas.
"""

usuario_activo=True
tiene_permiso=True

if usuario_activo and tiene_permiso:
  print("Acceso permitido")
else:
  print("Acceso denegado")

"""8. Completa la condición: se permite continuar si existe correo válido o teléfono válido."""

correo_valido = False
telefono_valido =True

if telefono_valido and correo_valido:
  print("Continuar registro")
else:
  print("Faltan datos de contacto")

"""9. Completa la condición usando not para mostrar el mensaje solo si la cuenta NO está
bloqueada.
"""

cuenta_bloqueada =False
if not cuenta_bloqueada:
  print("Puede operar")

"""**D. Estructura repetitiva for**

*Recorrer rangos y controlar iteraciones*

10. Completa range() para imprimir los valores 1, 2, 3, 4 y 5.
"""

for numero in range (1,6):
  print(numero)

"""11. Completa range() para imprimir 2, 4, 6, 8 y 10."""

for numero in range (2,11,2):
  print(numero)

"""12. Sin ejecutar, determina el valor final de suma."""

suma=0
for i in range(1,4):
  suma=suma+i
print(suma)

"""**Respuesta:** 6

13. Completa la condición y la actualización para imprimir los números del 1 al 5.
"""

numero = 1

while numero <= 5:
    print(numero)
    numero = numero + 1

"""14. El siguiente programa nunca termina. Corrige solo la línea que falta dentro del ciclo."""

numero = 1

while numero <= 5:
    print(numero)
    numero = numero + 1

"""**Respuesta:** Se agrega numero = numero + 1 para aumentar el valor de la variable en cada repetición y evitar que el ciclo sea infinito.

15. Completa el ciclo para permitir máximo 3 intentos. No modifiques las líneas ya escritas.
"""

intentos = 0

while intentos < 3:
    clave = input("Ingrese la clave: ")
    intentos = intentos + 1

print("Proceso finalizado")

"""**F. Elegir y combinar estructuras**    
for + if, while + condición y razonamiento sobre flujo

16. ¿for o while?
Escribe la estructura que elegirías en cada situación.

Procesar exactamente 10 mediciones: **for**   
Pedir una clave hasta que sea correcta: **While**  
Imprimir los números del 1 al 20: **for**  
Repetir un cálculo hasta que el error sea menor que 0.01: **while**

17. **Combina for + if**  
Completa el programa para recorrer del 1 al 12 y mostrar únicamente los múltiplos de 3.
"""

for numero in range (1,13):
  if numero %3 == 0:
    print(numero)

"""18. Escribe todas las líneas que producirá el programa."""

for numero in range(1, 8):
  if numero < 3:
    print(numero, "A")
  elif numero < 6:
    print(numero, "B")
  else:
    print(numero, "C")

"""**Respuesta:**  
1 A  
2 A  
3 B  
4 B  
5 B  
6 C  
7 C

**G. Del pseudocódigo a Python**  
Conserva la lógica y cambia la representación

19. Completa el código Python para que represente exactamente el pseudocódigo mostrado.
"""

nota = float(input("Nota: "))

if nota >= 3.0:
    print("Aprobado")
else:
    print("No aprobado")

"""20. Completa el programa Python equivalente al pseudocódigo."""

for i in range(1, 6):
    print(i)

"""**Reto integrador**  
Combina entrada, repetición y decisión sin utilizar listas ni funciones

Completa todos los espacios. Antes de ejecutar, prueba mentalmente tu solución con los
valores: 15, 18, 22, 25 y 30.
"""

for i in range(5):
    t = float(input("Temperatura: "))

    if t < 18:
        print("Baja")
    elif t <= 25:
        print("Normal")
    else:
        print("Alta")

"""**Respuesta:**  
15	Baja  
18	Normal  
22	Normal  
25	Normal  
30	Alta

**Autoevaluación rápida**

1.**¿Puedo explicar cuándo usar if, elif y else?**  
Sí. Entendí que if se utiliza para evaluar una condición, elif sirve para revisar otras opciones cuando la primera condición no se cumple y else se usa cuando ninguna de las condiciones anteriores se cumple.

2. **¿Puedo distinguir cuándo conviene for y cuándo while?**  
Sí. Aprendí que for se utiliza cuando quiero recorrer varios elementos o cuando sé cuántas veces necesito repetir una acción. En cambio, while se utiliza cuando necesito que una acción se repita mientras se siga cumpliendo una condición.

3. **¿Puedo identificar el riesgo de un ciclo infinito?**  
Sí. Comprendí que un ciclo infinito puede ocurrir cuando una condición siempre se mantiene verdadera y el programa no encuentra una forma de terminar la repetición. Por eso es importante revisar que la condición pueda cambiar durante la ejecución.

4. **¿Puedo traducir una decisión o repetición desde pseudocódigo a Python?**  
Sí. Con los ejercicios realizados he aprendido a pasar las decisiones y repeticiones del pseudocódigo a Python. Por ejemplo, puedo relacionar las condiciones con if, elif y else, y las repeticiones con for o while, dependiendo de lo que necesite realizar el programa.
"""